version: "3"

services:
  app:
    build: ./app
    container_name: application
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app-node
    networks:
      - application
    depends_on:
      - rabbitmq

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - "5432:5432"
    networks:
      - application

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq
    hostname: rabbitmq
    networks:
      - application
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}

networks:
  application:
    driver: bridge